// <auto-generated />
using LocalBusinessAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalBusinessAPI.Migrations
{
    [DbContext(typeof(LocalBusinessAPIContext))]
    [Migration("20200403183703_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LocalBusinessAPI.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BusinessAddress");

                    b.Property<string>("BusinessName");

                    b.Property<string>("BusinessType");

                    b.Property<string>("ClosingHour");

                    b.Property<string>("OpeningHour");

                    b.HasKey("BusinessId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            BusinessId = 1,
                            BusinessAddress = "120 NE Russell St, Portland, OR 97212",
                            BusinessName = "Toro Bravo",
                            BusinessType = "Restaurant",
                            ClosingHour = "6 PM",
                            OpeningHour = "11 AM"
                        },
                        new
                        {
                            BusinessId = 2,
                            BusinessAddress = "960 SE 11th Ave, Portland, OR 97214",
                            BusinessName = "Kachka",
                            BusinessType = "Restaurant",
                            ClosingHour = "8 PM",
                            OpeningHour = "12 PM"
                        },
                        new
                        {
                            BusinessId = 3,
                            BusinessAddress = "225 SW Ash St, Portland, OR 97204",
                            BusinessName = "BAES",
                            BusinessType = "Restaurant",
                            ClosingHour = "11 PM",
                            OpeningHour = "11 AM"
                        },
                        new
                        {
                            BusinessId = 4,
                            BusinessAddress = "3012 NE Alberta St, Portland, OR 97211",
                            BusinessName = "ROAR Cat Specialty Gift Shop",
                            BusinessType = "Shop",
                            ClosingHour = "6 PM",
                            OpeningHour = "11 AM"
                        },
                        new
                        {
                            BusinessId = 5,
                            BusinessAddress = "40 NW 10th Ave, Portland, OR 97209",
                            BusinessName = "MadeHere PDX",
                            BusinessType = "Shop",
                            ClosingHour = "6 PM",
                            OpeningHour = "11 AM"
                        },
                        new
                        {
                            BusinessId = 6,
                            BusinessAddress = "2340 NE Sandy Blvd, Portland, OR 97232",
                            BusinessName = "Providore Fine Foods",
                            BusinessType = "Shop",
                            ClosingHour = "6 PM",
                            OpeningHour = "10 AM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
